apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: multi-pod
spec:
  containers:
    - name: goserver-container
      image: go_server:alpha
      imagePullPolicy: Never
      ports:
        - containerPort: 3333
    - name: webserver-container
      image: webserver:beta
      imagePullPolicy: Never
      ports:
        - containerPort: 5173
